name: Manual
on: [workflow_dispatch]
jobs:
  generate_osmnames:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Build docker image
        run: docker compose build
      - name: Run generation
        run: docker compose run --rm osmnames
      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: osmnames_export
          path: |
            data/export
